// <auto-generated />
using System;
using GroupChat.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupChat.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20230508163844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroupChat.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorId = 1,
                            Description = "Description 1",
                            IsDeleted = false,
                            Name = "Group 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatorId = 8,
                            Description = "Description 2",
                            IsDeleted = false,
                            Name = "Group 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatorId = 5,
                            Description = "Description 3",
                            IsDeleted = false,
                            Name = "Group 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatorId = 10,
                            Description = "Description 4",
                            IsDeleted = false,
                            Name = "Group 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatorId = 1,
                            Description = "Description 5",
                            IsDeleted = false,
                            Name = "Group 5"
                        });
                });

            modelBuilder.Entity("GroupChat.Models.GroupMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SenderId");

                    b.ToTable("GroupMessages");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 8,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 1 from Group 1"
                        },
                        new
                        {
                            Id = 21,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 10,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 2 from Group 1"
                        },
                        new
                        {
                            Id = 31,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 3,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 3 from Group 1"
                        },
                        new
                        {
                            Id = 41,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 4,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 4 from Group 1"
                        },
                        new
                        {
                            Id = 51,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 4,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 5 from Group 1"
                        },
                        new
                        {
                            Id = 61,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 1,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 6 from Group 1"
                        },
                        new
                        {
                            Id = 71,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 4,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 7 from Group 1"
                        },
                        new
                        {
                            Id = 81,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 5,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 8 from Group 1"
                        },
                        new
                        {
                            Id = 91,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 5,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 9 from Group 1"
                        },
                        new
                        {
                            Id = 101,
                            GroupId = 1,
                            IsDeleted = false,
                            SenderId = 9,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 10 from Group 1"
                        },
                        new
                        {
                            Id = 12,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 4,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 1 from Group 2"
                        },
                        new
                        {
                            Id = 22,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 8,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 2 from Group 2"
                        },
                        new
                        {
                            Id = 32,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 6,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 3 from Group 2"
                        },
                        new
                        {
                            Id = 42,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 7,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 4 from Group 2"
                        },
                        new
                        {
                            Id = 52,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 9,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 5 from Group 2"
                        },
                        new
                        {
                            Id = 62,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 6,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 6 from Group 2"
                        },
                        new
                        {
                            Id = 72,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 7,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 7 from Group 2"
                        },
                        new
                        {
                            Id = 82,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 8,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 8 from Group 2"
                        },
                        new
                        {
                            Id = 92,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 5,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 9 from Group 2"
                        },
                        new
                        {
                            Id = 102,
                            GroupId = 2,
                            IsDeleted = false,
                            SenderId = 5,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 10 from Group 2"
                        },
                        new
                        {
                            Id = 13,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 1,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 1 from Group 3"
                        },
                        new
                        {
                            Id = 23,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 2,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 2 from Group 3"
                        },
                        new
                        {
                            Id = 33,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 1,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 3 from Group 3"
                        },
                        new
                        {
                            Id = 43,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 6,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 4 from Group 3"
                        },
                        new
                        {
                            Id = 53,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 9,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 5 from Group 3"
                        },
                        new
                        {
                            Id = 63,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 10,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 6 from Group 3"
                        },
                        new
                        {
                            Id = 73,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 4,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 7 from Group 3"
                        },
                        new
                        {
                            Id = 83,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 10,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 8 from Group 3"
                        },
                        new
                        {
                            Id = 93,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 1,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 9 from Group 3"
                        },
                        new
                        {
                            Id = 103,
                            GroupId = 3,
                            IsDeleted = false,
                            SenderId = 1,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 10 from Group 3"
                        },
                        new
                        {
                            Id = 14,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 4,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 1 from Group 4"
                        },
                        new
                        {
                            Id = 24,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 5,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 2 from Group 4"
                        },
                        new
                        {
                            Id = 34,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 8,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 3 from Group 4"
                        },
                        new
                        {
                            Id = 44,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 1,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 4 from Group 4"
                        },
                        new
                        {
                            Id = 54,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 8,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 5 from Group 4"
                        },
                        new
                        {
                            Id = 64,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 5,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 6 from Group 4"
                        },
                        new
                        {
                            Id = 74,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 6,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 7 from Group 4"
                        },
                        new
                        {
                            Id = 84,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 6,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 8 from Group 4"
                        },
                        new
                        {
                            Id = 94,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 6,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 9 from Group 4"
                        },
                        new
                        {
                            Id = 104,
                            GroupId = 4,
                            IsDeleted = false,
                            SenderId = 3,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 10 from Group 4"
                        },
                        new
                        {
                            Id = 15,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 8,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 1 from Group 5"
                        },
                        new
                        {
                            Id = 25,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 3,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 2 from Group 5"
                        },
                        new
                        {
                            Id = 35,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 8,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 3 from Group 5"
                        },
                        new
                        {
                            Id = 45,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 2,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 4 from Group 5"
                        },
                        new
                        {
                            Id = 55,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 1,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 5 from Group 5"
                        },
                        new
                        {
                            Id = 65,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 4,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 6 from Group 5"
                        },
                        new
                        {
                            Id = 75,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 10,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 7 from Group 5"
                        },
                        new
                        {
                            Id = 85,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 6,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 8 from Group 5"
                        },
                        new
                        {
                            Id = 95,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 8,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 9 from Group 5"
                        },
                        new
                        {
                            Id = 105,
                            GroupId = 5,
                            IsDeleted = false,
                            SenderId = 10,
                            SentAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Message 10 from Group 5"
                        });
                });

            modelBuilder.Entity("GroupChat.Models.GroupUserXREF", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupUserXREF");

                    b.HasData(
                        new
                        {
                            GroupId = 5,
                            UserId = 1
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 2
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 4
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 5
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 6
                        },
                        new
                        {
                            GroupId = 4,
                            UserId = 7
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 8
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 9
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("GroupChat.Models.MessageLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupMessageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupMessageId");

                    b.HasIndex("UserId");

                    b.ToTable("MessageLikes");

                    b.HasData(
                        new
                        {
                            Id = 113,
                            GroupMessageId = 11,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 115,
                            GroupMessageId = 11,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 116,
                            GroupMessageId = 11,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 117,
                            GroupMessageId = 11,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 118,
                            GroupMessageId = 11,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 119,
                            GroupMessageId = 11,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 120,
                            GroupMessageId = 11,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 212,
                            GroupMessageId = 21,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 213,
                            GroupMessageId = 21,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 214,
                            GroupMessageId = 21,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 215,
                            GroupMessageId = 21,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 217,
                            GroupMessageId = 21,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 220,
                            GroupMessageId = 21,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 311,
                            GroupMessageId = 31,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 314,
                            GroupMessageId = 31,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 315,
                            GroupMessageId = 31,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 316,
                            GroupMessageId = 31,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 317,
                            GroupMessageId = 31,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 319,
                            GroupMessageId = 31,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 412,
                            GroupMessageId = 41,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 414,
                            GroupMessageId = 41,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 416,
                            GroupMessageId = 41,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 417,
                            GroupMessageId = 41,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 418,
                            GroupMessageId = 41,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 512,
                            GroupMessageId = 51,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 514,
                            GroupMessageId = 51,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 516,
                            GroupMessageId = 51,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 517,
                            GroupMessageId = 51,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 518,
                            GroupMessageId = 51,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 520,
                            GroupMessageId = 51,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 611,
                            GroupMessageId = 61,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 614,
                            GroupMessageId = 61,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 615,
                            GroupMessageId = 61,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 616,
                            GroupMessageId = 61,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 711,
                            GroupMessageId = 71,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 715,
                            GroupMessageId = 71,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 716,
                            GroupMessageId = 71,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 718,
                            GroupMessageId = 71,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 811,
                            GroupMessageId = 81,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 812,
                            GroupMessageId = 81,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 813,
                            GroupMessageId = 81,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 814,
                            GroupMessageId = 81,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 817,
                            GroupMessageId = 81,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 818,
                            GroupMessageId = 81,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 819,
                            GroupMessageId = 81,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 820,
                            GroupMessageId = 81,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 913,
                            GroupMessageId = 91,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 915,
                            GroupMessageId = 91,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 916,
                            GroupMessageId = 91,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 917,
                            GroupMessageId = 91,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 918,
                            GroupMessageId = 91,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 1011,
                            GroupMessageId = 101,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1012,
                            GroupMessageId = 101,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 1014,
                            GroupMessageId = 101,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 1015,
                            GroupMessageId = 101,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 1019,
                            GroupMessageId = 101,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 123,
                            GroupMessageId = 12,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 124,
                            GroupMessageId = 12,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 125,
                            GroupMessageId = 12,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 126,
                            GroupMessageId = 12,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 127,
                            GroupMessageId = 12,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 130,
                            GroupMessageId = 12,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 221,
                            GroupMessageId = 22,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 223,
                            GroupMessageId = 22,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 224,
                            GroupMessageId = 22,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 226,
                            GroupMessageId = 22,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 229,
                            GroupMessageId = 22,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 230,
                            GroupMessageId = 22,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 328,
                            GroupMessageId = 32,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 329,
                            GroupMessageId = 32,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 330,
                            GroupMessageId = 32,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 422,
                            GroupMessageId = 42,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 425,
                            GroupMessageId = 42,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 426,
                            GroupMessageId = 42,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 428,
                            GroupMessageId = 42,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 429,
                            GroupMessageId = 42,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 521,
                            GroupMessageId = 52,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 525,
                            GroupMessageId = 52,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 527,
                            GroupMessageId = 52,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 530,
                            GroupMessageId = 52,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 621,
                            GroupMessageId = 62,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 624,
                            GroupMessageId = 62,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 627,
                            GroupMessageId = 62,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 630,
                            GroupMessageId = 62,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 721,
                            GroupMessageId = 72,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 722,
                            GroupMessageId = 72,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 724,
                            GroupMessageId = 72,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 725,
                            GroupMessageId = 72,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 729,
                            GroupMessageId = 72,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 822,
                            GroupMessageId = 82,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 823,
                            GroupMessageId = 82,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 824,
                            GroupMessageId = 82,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 826,
                            GroupMessageId = 82,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 827,
                            GroupMessageId = 82,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 829,
                            GroupMessageId = 82,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 927,
                            GroupMessageId = 92,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 928,
                            GroupMessageId = 92,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 1022,
                            GroupMessageId = 102,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 1023,
                            GroupMessageId = 102,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 1028,
                            GroupMessageId = 102,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 1029,
                            GroupMessageId = 102,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 1030,
                            GroupMessageId = 102,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 131,
                            GroupMessageId = 13,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 132,
                            GroupMessageId = 13,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 133,
                            GroupMessageId = 13,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 136,
                            GroupMessageId = 13,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 138,
                            GroupMessageId = 13,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 232,
                            GroupMessageId = 23,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 235,
                            GroupMessageId = 23,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 236,
                            GroupMessageId = 23,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 237,
                            GroupMessageId = 23,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 240,
                            GroupMessageId = 23,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 335,
                            GroupMessageId = 33,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 336,
                            GroupMessageId = 33,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 338,
                            GroupMessageId = 33,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 339,
                            GroupMessageId = 33,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 340,
                            GroupMessageId = 33,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 432,
                            GroupMessageId = 43,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 433,
                            GroupMessageId = 43,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 435,
                            GroupMessageId = 43,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 436,
                            GroupMessageId = 43,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 438,
                            GroupMessageId = 43,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 532,
                            GroupMessageId = 53,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 533,
                            GroupMessageId = 53,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 535,
                            GroupMessageId = 53,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 536,
                            GroupMessageId = 53,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 537,
                            GroupMessageId = 53,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 631,
                            GroupMessageId = 63,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 633,
                            GroupMessageId = 63,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 635,
                            GroupMessageId = 63,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 637,
                            GroupMessageId = 63,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 638,
                            GroupMessageId = 63,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 731,
                            GroupMessageId = 73,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 732,
                            GroupMessageId = 73,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 737,
                            GroupMessageId = 73,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 738,
                            GroupMessageId = 73,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 740,
                            GroupMessageId = 73,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 832,
                            GroupMessageId = 83,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 835,
                            GroupMessageId = 83,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 836,
                            GroupMessageId = 83,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 837,
                            GroupMessageId = 83,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 931,
                            GroupMessageId = 93,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 932,
                            GroupMessageId = 93,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 935,
                            GroupMessageId = 93,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 938,
                            GroupMessageId = 93,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 940,
                            GroupMessageId = 93,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 1031,
                            GroupMessageId = 103,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1032,
                            GroupMessageId = 103,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 1033,
                            GroupMessageId = 103,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 1035,
                            GroupMessageId = 103,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 1036,
                            GroupMessageId = 103,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 1038,
                            GroupMessageId = 103,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 1039,
                            GroupMessageId = 103,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 141,
                            GroupMessageId = 14,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 145,
                            GroupMessageId = 14,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 146,
                            GroupMessageId = 14,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 149,
                            GroupMessageId = 14,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 241,
                            GroupMessageId = 24,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 243,
                            GroupMessageId = 24,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 245,
                            GroupMessageId = 24,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 249,
                            GroupMessageId = 24,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 341,
                            GroupMessageId = 34,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 343,
                            GroupMessageId = 34,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 344,
                            GroupMessageId = 34,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 345,
                            GroupMessageId = 34,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 348,
                            GroupMessageId = 34,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 349,
                            GroupMessageId = 34,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 441,
                            GroupMessageId = 44,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 442,
                            GroupMessageId = 44,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 447,
                            GroupMessageId = 44,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 449,
                            GroupMessageId = 44,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 541,
                            GroupMessageId = 54,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 543,
                            GroupMessageId = 54,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 545,
                            GroupMessageId = 54,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 546,
                            GroupMessageId = 54,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 548,
                            GroupMessageId = 54,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 549,
                            GroupMessageId = 54,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 644,
                            GroupMessageId = 64,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 647,
                            GroupMessageId = 64,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 649,
                            GroupMessageId = 64,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 741,
                            GroupMessageId = 74,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 742,
                            GroupMessageId = 74,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 743,
                            GroupMessageId = 74,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 744,
                            GroupMessageId = 74,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 746,
                            GroupMessageId = 74,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 748,
                            GroupMessageId = 74,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 749,
                            GroupMessageId = 74,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 845,
                            GroupMessageId = 84,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 846,
                            GroupMessageId = 84,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 848,
                            GroupMessageId = 84,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 849,
                            GroupMessageId = 84,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 850,
                            GroupMessageId = 84,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 942,
                            GroupMessageId = 94,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 947,
                            GroupMessageId = 94,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 950,
                            GroupMessageId = 94,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 1041,
                            GroupMessageId = 104,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1042,
                            GroupMessageId = 104,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 1044,
                            GroupMessageId = 104,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 1045,
                            GroupMessageId = 104,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 1048,
                            GroupMessageId = 104,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 1049,
                            GroupMessageId = 104,
                            IsDeleted = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 1050,
                            GroupMessageId = 104,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 151,
                            GroupMessageId = 15,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 153,
                            GroupMessageId = 15,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 154,
                            GroupMessageId = 15,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 156,
                            GroupMessageId = 15,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 160,
                            GroupMessageId = 15,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 252,
                            GroupMessageId = 25,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 254,
                            GroupMessageId = 25,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 255,
                            GroupMessageId = 25,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 257,
                            GroupMessageId = 25,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 351,
                            GroupMessageId = 35,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 352,
                            GroupMessageId = 35,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 354,
                            GroupMessageId = 35,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 356,
                            GroupMessageId = 35,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 360,
                            GroupMessageId = 35,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 453,
                            GroupMessageId = 45,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 454,
                            GroupMessageId = 45,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 457,
                            GroupMessageId = 45,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 458,
                            GroupMessageId = 45,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 551,
                            GroupMessageId = 55,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 552,
                            GroupMessageId = 55,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 553,
                            GroupMessageId = 55,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 554,
                            GroupMessageId = 55,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 557,
                            GroupMessageId = 55,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 653,
                            GroupMessageId = 65,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 654,
                            GroupMessageId = 65,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 658,
                            GroupMessageId = 65,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 660,
                            GroupMessageId = 65,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 752,
                            GroupMessageId = 75,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 754,
                            GroupMessageId = 75,
                            IsDeleted = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 755,
                            GroupMessageId = 75,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 756,
                            GroupMessageId = 75,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 851,
                            GroupMessageId = 85,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 852,
                            GroupMessageId = 85,
                            IsDeleted = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 853,
                            GroupMessageId = 85,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 953,
                            GroupMessageId = 95,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 956,
                            GroupMessageId = 95,
                            IsDeleted = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 957,
                            GroupMessageId = 95,
                            IsDeleted = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 958,
                            GroupMessageId = 95,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 960,
                            GroupMessageId = 95,
                            IsDeleted = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 1051,
                            GroupMessageId = 105,
                            IsDeleted = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1053,
                            GroupMessageId = 105,
                            IsDeleted = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 1055,
                            GroupMessageId = 105,
                            IsDeleted = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 1058,
                            GroupMessageId = 105,
                            IsDeleted = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 1060,
                            GroupMessageId = 105,
                            IsDeleted = false,
                            UserId = 10
                        });
                });

            modelBuilder.Entity("GroupChat.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@mail.com",
                            IsDeleted = false,
                            Name = "User 1",
                            Password = "password1",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@mail.com",
                            IsDeleted = false,
                            Name = "User 2",
                            Password = "password2",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@mail.com",
                            IsDeleted = false,
                            Name = "User 3",
                            Password = "password3",
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4@mail.com",
                            IsDeleted = false,
                            Name = "User 4",
                            Password = "password4",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user5@mail.com",
                            IsDeleted = false,
                            Name = "User 5",
                            Password = "password5",
                            Username = "user5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "user6@mail.com",
                            IsDeleted = false,
                            Name = "User 6",
                            Password = "password6",
                            Username = "user6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "user7@mail.com",
                            IsDeleted = false,
                            Name = "User 7",
                            Password = "password7",
                            Username = "user7"
                        },
                        new
                        {
                            Id = 8,
                            Email = "user8@mail.com",
                            IsDeleted = false,
                            Name = "User 8",
                            Password = "password8",
                            Username = "user8"
                        },
                        new
                        {
                            Id = 9,
                            Email = "user9@mail.com",
                            IsDeleted = false,
                            Name = "User 9",
                            Password = "password9",
                            Username = "user9"
                        },
                        new
                        {
                            Id = 10,
                            Email = "user10@mail.com",
                            IsDeleted = false,
                            Name = "User 10",
                            Password = "password10",
                            Username = "user10"
                        });
                });

            modelBuilder.Entity("GroupChat.Models.GroupMessage", b =>
                {
                    b.HasOne("GroupChat.Models.Group", "Group")
                        .WithMany("GroupMessages")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupChat.Models.User", "Sender")
                        .WithMany("GroupMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GroupChat.Models.GroupUserXREF", b =>
                {
                    b.HasOne("GroupChat.Models.Group", "Group")
                        .WithMany("GroupUserXREF")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupChat.Models.User", "User")
                        .WithMany("GroupUserXREF")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupChat.Models.MessageLike", b =>
                {
                    b.HasOne("GroupChat.Models.GroupMessage", "GroupMessage")
                        .WithMany("MessageLikes")
                        .HasForeignKey("GroupMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupChat.Models.User", "User")
                        .WithMany("MessageLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroupChat.Models.Group", b =>
                {
                    b.Navigation("GroupMessages");

                    b.Navigation("GroupUserXREF");
                });

            modelBuilder.Entity("GroupChat.Models.GroupMessage", b =>
                {
                    b.Navigation("MessageLikes");
                });

            modelBuilder.Entity("GroupChat.Models.User", b =>
                {
                    b.Navigation("GroupMessages");

                    b.Navigation("GroupUserXREF");

                    b.Navigation("MessageLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
